### ISSUE TITLE
Cannot create more than one storage controller in yml config

### ISSUE THREAD

**Issue by josephgorse** [InfraSIM/infrasim-compute#213]
I am debugging an issue with @mtannous
We are trying to make a yml configuration that contains the following:
```
compute:
    boot_order: ncd,reboot-timeout=10000
    cpu:
        quantities: 2
        type: Haswell

    memory:
        size: 1024

    storage_backend:
        #Set drive list and define drive attributes
        -
            controller:
                type: ahci
                max_drive_per_controller: 8
                drives:                
                -
                    size: 100
                -
                    size: 100
                -
                    size: 100
                -
                    size: 100
                -
                    size: 100
                -
                    size: 100
        -
            controller:
                type: ahci
                max_drive_per_controller: 8
                drives:
                -
                    size: 100
```

With that in the configuration, `infrasim node start` fails. When we take out the second controller block, we have no issues. It looks like the current implementation does not support multiple controller blocks. 

We dug through the source code and found this line, where the drives within the controller are parsed. It looks like it would be possible to parse multiple controllers here by wrapping it around another for loop. 
https://github.com/InfraSIM/infrasim-compute/blob/ccfb3925e3751da3030a20ff994b0e9f0650a6fc/infrasim/model.py#L563
